# This is the configuration image, which AFAICT uses a Docker image just to
# send a single file--the docker-compose.yaml file--to Antithesis.
FROM scratch
COPY docker-compose.yaml /docker-compose.yaml
